### ISSUE TITLE
[REQ] MacOS port

### ISSUE THREAD

**Issue by gowl** [ThePBone/GalaxyBudsClient#150]
I recently got a 13" MacBook Pro and was in love with your program back when I used windows. Are there any plans for a macOS port at all? I've seen that there was a Linux one, so thought maybe it wouldn't be as impossible as I thought.

**Comment by ThePBone** [comment]
I don't plan to support it at the moment, but anyone is welcome to add support. There are several implementations for platform-specific services missing. I made a small list of what is still missing on macOS: https://github.com/ThePBone/GalaxyBudsClient/issues/115#issuecomment-767416884 (only the Bluetooth stuff is mandatory; the other things listed there are optional)

I'll close this issue since we already have #115
