### ISSUE TITLE
[REQ] Game Mode Gone?

### ISSUE THREAD

**Issue by Kasur1309** [ThePBone/GalaxyBudsClient#164]
Hello!

i used this client a few months ago. Back then it supported a low latency game mode! But this feature seems to be gone now. Can you please add it back or at least tell me in which version it was still supported so that i can downgrade to it? Thank you.

**Comment by ThePBone** [comment]
The Gaming Mode option is not functional on Windows since Gaming Mode only supports Android devices running OneUI 3 or later because a special closed-sourced audio codec developed by Samsung is required which is also available on these devices.
There is no point in including an option that has no effect on computers or other non-android devices.

If you still want the option regardless, you need to use version 3.2, but it won't make an actual difference.
