### ISSUE TITLE
[BUG] : Battery level of the case is at 101%

### ISSUE THREAD

**Issue by adithya0** [ThePBone/GalaxyBudsClient#165]
The battery level on the desktop app, for the case shows 101% constantly.
I updated the Galaxy buds today and noticed this.

Attached are the screen shots from the desktop app, the Android app(official) and the raw data dumps.
[GBM - Desktop Screen shots.pdf](https://github.com/ThePBone/GalaxyBudsClient/files/6033037/GBM.-.Desktop.Screen.shots.pdf)
![Screenshot_20210223-214737_Galaxy Buds Live](https://user-images.githubusercontent.com/46767792/108940620-b0f86800-7621-11eb-939d-173c52bfec56.jpg)
[datadump.zip](https://github.com/ThePBone/GalaxyBudsClient/files/6033040/datadump.zip)

**Comment by ThePBone** [comment]
What version of this app are you using? I tried to fix this issue on version 4.1; if you happen to use an older version, updating could help. Otherwise, I'll need to double-check my code.

**Comment by adithya0** [comment]
Tim,

 

I am using V4.1.0.0

**Comment by adithya0** [comment]
Sorry. It may be a bad report. With the buds in the case the App reports the correct battery percentage. 
When wearing the buds even with the case open, the app reports 101%. My assumption was that the with the case open(even without the buds in the case), that it will report the correct battery percentage. However it may be a wrong assumption on my end.
Sorry for the trouble.

**Comment by giovanniro98** [comment]
I have this issue when I connect buds+ to pc, previously connected to my phone.

**Comment by mihaivolmer** [comment]
Hello. 
I have the same issue with Galaxy Buds Pro. I have the V4.1.0.0 version of the software. Before the update this issue was not present.
If I put one earphone back in the case and take it back out it will show the correct percentage. However, after minimizing the application it will return to 101% battery for the case.
I can provide more info if needed.
Mihai

**Comment by ThePBone** [comment]
Oops, I thought this issue was only about the Buds Pro, but the original author of this message clearly attached a screenshot with a pair of Buds Live.

I've enable that check for all models. (commits a5468c28f1d41a8c8c6c8cb198ae0f42de9c28c0, 9c8b84bb2fe96d2c6d1a61f5f361df9d3bdf64e0)

As soon as the cloud VM finishes compiling, you can download updated binaries at the bottom of this page: https://github.com/ThePBone/GalaxyBudsClient/actions/runs/621091643 (GitHub account required to download)

**Comment by mihaivolmer** [comment]
Thanks! I checked and it works correctly now (for buds plus).
However, I notice that with the current firmware update, the buds no longer provide case battery updates when they are not placed in the case. Because of this, we only a 0% case battery when the headphones are worn. 
I suggest trying to cache the latest known case battery reading until the next valid reading (!= 101). I think it's more useful than showing 0% (or nothing, as it happens at the moment in the Galaxy Wearable app). Maybe add a tool-tip to explain it is not a live reading.

**Comment by ThePBone** [comment]
Hmm, I'll look into it. There might be an alternative way to read out case battery information on this new firmware even when the case is closed, but I need to check whether that method is reliable at all first.

**Comment by ThePBone** [comment]
It looks like the case completely disables its Bluetooth connection to the earbuds and stops sharing battery information when keeping it closed for several seconds, probably to lower power consumption. 

For now, I'll hide the case stuff if the earbuds return an invalid value. (3f4baa95)

Build: https://github.com/ThePBone/GalaxyBudsClient/actions/runs/621687946

**Comment by mihaivolmer** [comment]
Hmm, I don't think the case ever provided live battery readings when the earbuds are not in the case. Also, it didn't seem to matter whether the case was opened or closed. 
The earbuds seemed to provide the latest known case battery. If I were to charge the case while using the earbuds, the battery level would not be updated (applies to both Galaxy Wearable app and your software).

**Comment by ThePBone** [comment]
Oh okay, I never noticed this behaviour. Maybe I'll cache the case battery after all.
