### ISSUE TITLE
[REQ] Get accelerometer or IMU data?

### ISSUE THREAD

**Issue by tcboy88** [ThePBone/GalaxyBudsClient#180]
Do you know anyway to get accelereomter or IMU data?

**Comment by ThePBone** [comment]
Yes, there are a few ways to obtain accelerometer readings; however, the data is refreshed rather slowly in most cases. I don't know how accurate it is either.

### Method 1 - Dump raw sensor data using debug commands (All Buds models)

You can decode and observe incoming Bluetooth serial messages using the developer mode in this app:

1. Within the app, navigate to 'Options > Developer options > Bluetooth socket'
2. Now, a new window should appear. It will display incoming data and allow you to inspect it (only if I've added a decoder for it though).
3. On the bottom-right side, you can send your own messages to the earbuds. In the first dropdown box, select: `DEBUG_GET_ALL_DATA` and in the second dropdown-box select: `Request` and hit "Send"
4. The buds should now respond with a message of type `DEBUG_GET_ALL_DATA`; you can find it looking at the table in the top-right corner
5. Click on the `DEBUG_GET_ALL_DATA` response in this table, and you can inspect the properties of that message below. Look for `LeftAcceleratorX` and so on.

Again, this method is rather slow and is probably a bit inaccurate, but it works for all Galaxy Buds models. I can also write a small script to dump this info automatically if you should need it.

### Method 2 - Reuse the 360° spatial audio feature (Buds Pro only)

You could also reuse the accelerometer data provided by the new spatial audio feature bundled with the Buds Pro. It is much faster and designed to be used with minimal latency and high accuracy.

Because I don't own a pair of Buds Pro, I haven't implemented decoders for Bluetooth messages containing spatial accelerometer data (these are transmitted within messages of type `SPATIAL_AUDIO_DATA` and `SPATIAL_AUDIO_CONTROL`), so you would need to figure that out yourself.

**Comment by RangerMauve** [comment]
Is there a fund to get you Galaxy Buds Pro? :P I'd be down to pitch in 20 bucks.

**Comment by tcboy88** [comment]
me too!

**Comment by ThePBone** [comment]
I've set up a donation page some time ago: https://ko-fi.com/thepbone

I would appreciate any support if you are interested. I'd use the money that comes together to get a pre-owned pair from eBay, to save a bit of money when I find a good deal.

**Comment by ThePBone** [comment]
I'll try to look into this soon, I got a somewhat cheap offer for 99 EUR. Unfortunately, the eBay seller accidentally shipped the package with the Buds Pro to an invalid address (typo), so it could take about two weeks until I finally receive them.

**Comment by ThePBone** [comment]
This feature is now available; you can download a precompiled build from the GitHub Action sections or use this mirror: https://nightly.timschneeberger.me/galaxybudsclient/GalaxyBudsClient_Setup_64bit_pre4.1.1.1-Headtracking-e5ffb1.zip

Demo GIF: https://imgur.com/a/Gu4pDQl (Navigate to 'System > Dump spatial data')

I can also write a small python script if you need it as a standalone thing for integration with something else.

**Comment by RangerMauve** [comment]
That's amazing! Thank you for all the cool stuff you're making. 💜

**Comment by tcboy88** [comment]
> 
> 
> This feature is now available; you can download a precompiled build from the GitHub Action sections or use this mirror: https://nightly.timschneeberger.me/galaxybudsclient/GalaxyBudsClient_Setup_64bit_pre4.1.1.1-Headtracking-e5ffb1.zip
> 
> Demo GIF: https://imgur.com/a/Gu4pDQl (Navigate to 'System > Dump spatial data')
> 
> I can also write a small python script if you need it as a standalone thing for integration with something else.

It will be really great if you can provide python script for easier integration with other stuffs =)

**Comment by ThePBone** [comment]
@tcboy88 I've published a minimal python script here: https://github.com/ThePBone/BudsPro-Headtracking

Check `Headtracking.py` for an example of how to integrate it with other stuff.
