### ISSUE TITLE
[REQ] - Please ADD microphone volume BOOST

### ISSUE THREAD

**Issue by Fasto5** [ThePBone/GalaxyBudsClient#193]
Hi there - AWESOME app!

However, I am finding on w10 that the micorphone volume on the Galaxy Buds is VERY low. Please add a 'Mic Boost' slider, much like you have created for the ambient noise boost section (but for the mic).

Background for feature request: 

I've adjusted all settings possible in windows - my laptop mic is STILL much louder. 

This is very evident when using applications such as Zoom which allows microphone volume to be turned up very easily.  

My laptop mic is in a normal mid-range to high level, yet the Galaxy buds mic is only at the 1/3 level which is ridiculous given they are only 20 cm from my mouth and that they work completely when using a samsung phone. 

I was researching and found your app on XDA and it's great - but I was specifically hoping for a 'Mic Boost' slider, much like you have created for the ambient noise boost section (but for the mic). 

If you could add that feature I think it would help a lot of people who are also complaining of the same problem on Windows (as can be seen on the samsung forums: [https://us.community.samsung.com/t5/Galaxy-Buds/Galaxy-buds-volume-is-low/td-p/1174157/page/2]

Thanks again for making your app and for considering my feature request!

**Comment by ThePBone** [comment]
Hey, unfortunately, implementing a microphone gain slider similar to the ambient sound settings is not possible in this app. This is because, on Windows, the Bluetooth audio streams (including their volumes) are encoded in a special protocol which is entirely handled by closed-source Bluetooth drivers provided by the manufacturer of your Bluetooth card. External apps can't alter any settings directly within these Bluetooth drivers or send their own audio-control commands over Bluetooth (to change A2DP volume settings) due to security reasons.

Apart from the Windows sound settings, the only way to boost the mic would be to use an app like Voicemeeter, which can further amplify the incoming audio stream from the microphone; however, this would probably degrade the audio quality quite a bit.
