### ISSUE TITLE
[REQ] How about showing the earbuds status clearly in the battery pop-up window if they are wearing them or in the case?

### ISSUE THREAD

**Issue by 4647sjs** [ThePBone/GalaxyBudsClient#199]
**Is your feature request related to a problem? Please describe.**

It's not a big problem, but I'm suggesting it because I want to know the status of the earbuds clearly in the battery pop-up window.

**Describe the solution you'd like**

If the earbuds are in the case, make the icon transparent.
If you wear it, make the icon back to its original state.
(You can clearly check if the earbuds are in the case.)

**Describe alternatives you've considered**

**Additional context**

Thank you for reading it.

**Comment by ThePBone** [comment]
So you mean you also want an option to activate the popup when the buds are removed/inserted from/into the case?
That shouldn't be a big issue, I can look into that soon.

However, I won't be able to make them transparent when they are in the case, because I'm already making them transparent when they are disconnected. I just need to display these wear/case states a bit differently then.

**Comment by 4647sjs** [comment]
Yes, I look forward to seeing the function applied soon.
Thank you.

**Comment by ThePBone** [comment]
Added. You can download the latest build at the bottom of this page as soon as the cloud worker has finished building the project (takes ~10 minutes): https://github.com/ThePBone/GalaxyBudsClient/actions/runs/810845877

The popup does not activate when an earbud is inserted into the case though, because they just report too many false positives even though the wearable state didn't change.
