### ISSUE TITLE
[REQ] Display codec information & switch codec

### ISSUE THREAD

**Issue by MollyBe** [ThePBone/GalaxyBudsClient#209]
I would like to view codec information & change codec inside GBM. 

Detailed codec information could be available in GBM - System - View System Information, this could include:
- Which codec the device supports
- Which codec the computer supports
- Which codec is currently used

Codec and bitrate could be displayed in the battery pop up & in the dashboard image
- If a scalable codec is being used this could be a dynamic value

In the View System Information menu or GBM - Advanced Settings an option to choose which codec is used

There are only non-free / non-open source programs available to view codec information of the device and display the codec selected by the computer on Windows 10. I am not aware of a program that can change which codec is being used or can display the codecs supported by the computer.

Here an article about researching which codec is being used (A2dpStreaming) and in the comments which codecs are supported by the device on Windows 10 (A2dpAvailableRemoteCodec):
https://helgeklein.com/blog/2020/09/how-to-check-which-bluetooth-a2dp-audio-codec-is-used-on-windows/

**Comment by ThePBone** [comment]
I can try to add an option to view codec information; however, I won't be able to add another option to switch codecs. This is because codecs are handled and chosen by the Bluetooth driver. Due to the closed nature of Windows, you can not manipulate how these drivers behave and what they chose. The only workaround would be to write your own Bluetooth driver with an explicit codec switch setting.

About the scalable codec: Even if you are able to switch codecs, you will never be able to enable the scalable codec on Windows because Samsung never published the audio codec in the first place. Unless, Samsung is willing to open-source or port their codec to Windows, we will not be able to use it there. On Windows you could only use the SBC and AAC codec with the Buds.

The codec information stuff is a bit out of scope for a project like this which only communicates to the earbuds via the RFCOMM protocol and leaves A2DP untouched, but I'll see if I can add some basic additional info.

**Comment by MollyBe** [comment]
Thanks, it would be nice to view codec information. I have checked mine and it is currently using SBC, it seems AAC is still only available in the Windows Insider's builds. I am not sure what the bitrate I am getting with SBC and it seems AAC may only provide 256kb/s. In that case SBC might be the better choice and AAC could be a downgrade.

![image](https://user-images.githubusercontent.com/51837460/117444533-e41c7900-af39-11eb-9e73-2c59a9f2c018.png)

After learning about the codecs supported by the buds, it is bewildering that Samsung wouldn't want their codec available on as many platforms as possible and have the device support as many codec's as possible. With the price of them already halving, it is easy to imagine them being able to include those costs in the price.

I forgot to mention A2dp also reports the reported device delay, it would be nice if this could also be included.

**Comment by ThePBone** [comment]
I had a closer look at this, and I won't be able to add this unless I implement it as a paid feature or someone sponsors me.
This is because viewing codec information via 3rd-party software is ONLY possible through a custom hardware-level driver. 
**However, on Windows, all drivers must be signed with a commercial EV code signing certificate.**
These EV certificates are very costly (starting with 309 EUR per year), and they are only designed for companies making it much harder for an individual to obtain one.
Apart from the financial issue, embedding a custom driver in this application is out of scope for this project anyway.

> There are only non-free / non-open-source programs available to view codec information of the device and display the codec selected by the computer on Windows 10. I am not aware of a program that can change which codec is being used or can display the codecs supported by the computer.

This is also why there are no open-source or free programs available for this. AFAIK, it is currently impossible to manipulate which codec is used, even by using a custom system driver unless you manage to modify your Bluetooth driver provided by your Bluetooth chipset manufacturer (however, modifying it will cause its EV certificate to become invalid so that Windows would reject the modified driver anyway).

**Comment by MollyBe** [comment]
That might explain why Windows doesn't display the codec naively lol!

**Comment by superbonaci** [comment]
@MollyBe what app are you using to view the codec information, that on your screenshot? Is that on Windows?
