### ISSUE TITLE
[BUG] "No paired devices found" with connected USB Bluetooth Dongle

### ISSUE THREAD

**Issue by fam4r** [ThePBone/GalaxyBudsClient#238]
**Describe the bug**  
Galaxy Buds Manager reports the message "No paired devices found" even if the Buds are connected successfully to a USB Bluetooth adapter.
Note: the reported issue has been observed in a laptop with an internal Bluetooth adapter (also tried to disable it) and a connected USB Bluetooth adapter.

**To Reproduce**  
1. Run the GalaxyBudsClient (`./GalaxyBudsClient_Linux_64bit_Portable.bin`)
2. Press "Continue"
3. Observe the problem

**Expected behavior**  
The paired device is found.

**Desktop (please complete the following information):**  
 - OS: Arch Linux
 - Application version: 4.2

**Log files**  
[application.log](https://github.com/ThePBone/GalaxyBudsClient/files/6695401/application.log)

```
2021-06-22 16:47:45.429 +02:00 [DBG] Linux.BluetoothService: Using Bluetooth adapter: hci1
```

**Comment by lightningjim** [comment]
I have a similar issue on my desktop. I have to use the USB because my motherboard's bluetooth isn't v5

Works fine in Windows, same issue in Linux/Pop! OS.

However I've not found a way to in OS side yet disable only the Bluetooth to test that part either.

Having the ability to change BT device might be useful here?

**Comment by StephenFluin** [comment]
Same issue I think.

I found a config.json, but it seems like there's no config or command line flag to select which bluetooth device is used. My headphones are connected to hci1, but the app only looks on hci0. :(

**Comment by lightningjim** [comment]
Confirmed this should fix it overall
I am trying to figure out the best way to get https://unix.stackexchange.com/a/243135 to work for disabling the built-in USB 
But that managed to get the USB named as hci0, disabled the built-in from Linux (authorized = 0), paired my Galaxy Buds, and they showed up

So the fact that this attaches to hci0 only is in fact the problem here.

**Comment by ThePBone** [comment]
It's very likely that this is the issue.
I'll try to add an option to change this without modifying your system configuration.

**Comment by ThePBone** [comment]
Sorry, accidentally closd this :sweat_smile:

**Comment by ThePBone** [comment]
For now, the app searches for an environment variable called `BT_ADAPTER`. 

Override the Bluetooth adapter like this:
```bash
export BT_ADAPTER="hci1"
```

You can grab updated binaries here: https://github.com/ThePBone/GalaxyBudsClient/actions/runs/1275520222
