### ISSUE TITLE
[BUG] Trojan:Win32/FormBook.AVP!MTB - Windows Defender

### ISSUE THREAD

**Issue by brentoncollins** [ThePBone/GalaxyBudsClient#242]
**Describe the bug**  
Windows defender flagging an issue with the installer. Trojan:Win32/FormBook.AVP!MTB - Windows Defender

**To Reproduce**  
Issue when downloaded

**Screenshots**  
![image](https://user-images.githubusercontent.com/25838340/124215710-25d73380-db27-11eb-96b9-4f76eb9b3bf8.png)

**Desktop (please complete the following information):**  
 - OS: Windows 10 SOE 21.03

 - Application version: 4.2

**Additional context**  
On work PC and don't want to get in the crap for bypassing windows defender.

**Comment by ThePBone** [comment]
It looks like Microsoft messed something up because other apps like tautulli here affected to: https://www.reddit.com/r/Tautulli/comments/ob8ef3/blocked_by_windows_security/

Microsoft already pushed out new Window Defender intelligence updates, which fix this false-positive issue.

You can find instructions on how to manually update them here (if it didn't happen automatically already): https://www.microsoft.com/en-us/wdsi/defenderupdates

I've also sent the affected binary to the Microsoft Defender review team, to be sure.

**Comment by ThePBone** [comment]
Also, this only seems to affect the installer program.
Alternatively, you can also download a portable version of this app (no installer or admin privileges required) here: https://github.com/ThePBone/GalaxyBudsClient/actions/runs/974165003

At the bottom of the page, you can find the standalone version called 'GalaxyBudsClient_win64_portable.exe' (GitHub account required to download these build artifacts, though).

**Comment by brentoncollins** [comment]
Thank you, this is correct.
