### ISSUE TITLE
[BUG] Buds Live - Touch not working

### ISSUE THREAD

**Issue by DarkAllMan** [ThePBone/GalaxyBudsClient#247]
**Describe the bug**  
When I connect my W10 and my Buds Live. Touch is not working. I configured touch panel to do commands, but I hear no validation sound and it is not doing the shortcurts

**To Reproduce**  
Touch buds live

**Expected behavior**  
Hear confiration sound + do command

**Screenshots**  
![image](https://user-images.githubusercontent.com/1582343/128183916-5f971709-9238-4846-8b09-bf3cf7f03726.png)

**Desktop (please complete the following information):**  
 - OS: Windows 10 20H2 x63, build: 19042.1110
 - Application version: 
 
![image](https://user-images.githubusercontent.com/1582343/128184350-43ffcfd7-baa7-48f6-8d5f-593ef66d815e.png)

**Log files**  
[application.log](https://github.com/ThePBone/GalaxyBudsClient/files/6931392/application.log)

**Comment by badzz** [comment]
It never worked for me even before using this tool.
It works when using stereo (A2DP) output but not when using Hands Free (HSP). 
However phone tools (teams, signal, skype ,..) works only when using Hands Free but the touch does not work with this setup.
![image](https://user-images.githubusercontent.com/6543969/130457753-01613c04-9e6b-4211-a8af-341602faa64f.png)

**Comment by badzz** [comment]
I dont know if it is the same problem as me (described above), but I came to realize that this is expected behavior. Using Hands-Free, touch action can only end calls and accept, you can't up and down volume or mute the mic.  At least, this is what he does when connecting to the phone during calls (check the official samsung documentation)
If your problem happens when using the "stereo" device(see screenshot above), then it is not the same problem, it works for me.

**Comment by ThePBone** [comment]
Yes, this is correct. When using the HFP Bluetooth profile, the earbuds think they are being used in a voice call and change the touch actions. While using HFP, the touchpads can only be used to answer/decline/... calls (only if the host device supports this as well); the regular touch actions are unavailable.

Select 'Headphones' instead 'Headset' to fix this.
