### ISSUE TITLE
[BUG] Firmware Update Timeout

### ISSUE THREAD

**Issue by AverageHumanoid** [ThePBone/GalaxyBudsClient#251]
I've been trying to update the firmware on my Buds Live from version R180XXU0ATH2 to R180XXU0AUB5. Whenever the process reaches about 60% it would always fail with a timeout error.

**Screenshots**  
![Screenshot](https://i.imgur.com/giRbKxp.png)

**Desktop (please complete the following information):**  
 - OS: Ubuntu 20.04
 
 - Application version: v4.2.1

**Log files**  
https://pastebin.com/raw/ufD4WwxV

**Comment by ThePBone** [comment]
Hey, for some reason, the firmware upload process is very slow on your machine. This could be either due to the Bluetooth chip not supporting high transport rates or an issue with the Bluetooth driver.

Anyway, the firmware installer has a time limit of 10 minutes for the whole copy process set and cancels the upload when it takes too long (to avoid unexpected freezes).

I've changed the timeout duration for the copy operation to avoid premature cancellations; you can download binaries with the fix included here: https://github.com/ThePBone/GalaxyBudsClient/actions/runs/1121090141

**Comment by AverageHumanoid** [comment]
Thank you very much! [This](https://www.newegg.ca/riitop-pce-1200nw-pci-express/p/0XM-00FG-00007) is the WiFi/Bluetooth adapter that I bought for my PC. I tried searching around but I didn't see any kernel module parameters or anything in `/etc/bluetooth/main.conf` that I could edit to increase the bandwidth.
