### ISSUE TITLE
Adjust internal (hardware) volume

### ISSUE THREAD

**Issue by superbonaci** [ThePBone/GalaxyBudsClient#29]
Android and iOS adjust software and hardware volume so they "match", but what happens on Windows, is that with volume buttons of the keyboard, you control the software volume. Buds have its own internal hardware volume which can be controlled separately. I'm not sure is latest version of Windows 10 2004 fixed this (because added support for headsets battery level except for Apple products), anyway could be interesting to have the values displayed by the app itself, and see if the values change when I change volume level on Windows with keyboard.

I thinks this issue is related:
[Is there any way to control connected bluetooth device volume in linux using command?](https://stackoverflow.com/questions/28191350/is-there-any-way-to-control-connected-bluetooth-device-volume-in-linux-using-com)

**Comment by ThePBone** [comment]
For some reason I never had this issue on Windows, even with builds before 2004 which is a bit strange.

Anyway, the rfcomm interface I'm using does not report the internal volume levels (there are a few exceptions with debug SPP messages, but those are very unreliable and are only present on the Buds+ iirc).

So in this case we'd need to talk to the AVRCP interface. This is easily possible on Linux but not on Windows, since its Bluetooth drivers are completely sealed off as they have no interface for third-party developers. (This is why Wireshark has no Bluetooth snoop mode on Windows).
Therefore, this feature is not really possible to implement on Windows, at least not without hacky and rather unreliable workarounds to guess the internal volume.

You could try to enable 'absolute volume' in your AVRCP driver instead:
<https://winaero.com/blog/enable-or-disable-bluetooth-absolute-volume-in-windows-10/>

**Comment by superbonaci** [comment]
Did some more tests and in fact volume levels adjusts always. on both android and W10, according to sound level set on operating system. So when you connect the Buds to operating system, the internal earphones volume automatically adjusts to that. Means I can have different volume levels on each host device and the buds adapt.
