### ISSUE TITLE
[REQ] Any suggestions for getting one earbud upgraded from R175XXU0ASLE?

### ISSUE THREAD

**Issue by emosenkis** [ThePBone/GalaxyBudsClient#304]
I recently received a replacement right earbud that I bought on eBay. After struggling to get it linked to the left earbud (I believe that I eventually succeeded since the case blinked green, the device names now match, and my devices seem to see only one or the other but never both), I came upon this project. Using it, I discovered that the right earbud I just got has firmware from 2019 installed, the official Android app shows it as R175XXU0ASLE. Trying to update the firmware of either earbud using the official Android app tells me to connect both earbuds and trying using this project gives me an error about battery level being too low (they're both fully charged and they show as 99% in the dashboard). I've tried downgrading the official Android app to one from mid-2020 but it still requires both earbuds. Do you have any advice for getting off of R175XXU0ASLE so I can get the two earbuds connected at the same time?

**Comment by emosenkis** [comment]
I tried compiling with the battery checks commented out in `FirmwareTransferManager.cs` and now I get this instead:

```
[10:45:41 DBG] FirmwareRemoteClient: Downloading firmware 'R175XXU0AUK1'...
[10:45:43 DBG] FirmwareTransferManager: Status changed to InitializingSession
[10:45:44 DBG] FirmwareTransferManager.OnMessageReceived: Session result is 144
[10:45:44 ERR] FirmwareTransferManager.OnError: GalaxyBudsClient.Model.Firmware.FirmwareTransferException: SessionFail: fw_fail_session
[10:45:44 DBG] FirmwareTransferManager: Status changed to Ready
```
There's not much more to see in the dump file:
[dump.zip](https://github.com/ThePBone/GalaxyBudsClient/files/7940186/dump.zip)

**Comment by ThePBone** [comment]
I'm guessing that the Galaxy Buds have an additional battery check built into their firmware, which returns the error code early on when attempting to open a firmware transfer session.

No idea what is going on there and whether there's a workaround. If there really is some kind of firmware-side check, then the chances are probably low to get it working.

**Comment by gledy2** [comment]
Hi, first off thanks for creating this. I just wondered if there was any updates on this, running into the same issue, my partner lost a bud plus, bought her a replacement which was on the latest firmware r175xxu0auk1, the previous one was r175xxu0asle. Unable to upgrade the firmware in the official app due to not both being connected at once led me here. Trying to downgrade the replacement to the earliest fw version or any others leads to the battery level issue (battery too low, please charge your earbuds to over 15% first). Connecting only to the other bud, it wont upgrade (fw_fail_session). I just wondered if there is any solution, or ideas to try, or a way to force the fw to upgrade. I also assume that the buds will update individually on here? Thanks

**Comment by emosenkis** [comment]
@gledy2 maybe we can swap to get two on the same version? Email me at `<first name>@<last name>.net` if you're interested

**Comment by gledy2** [comment]
> @gledy2 maybe we can swap to get two on the same version? Email me at `<first name>@<last name>.net` if you're interested

Hi, i would have, but unfortunately the replacement one i got was right too, the left is on the old firmware
