### ISSUE TITLE
[REQ] Minimize to System Tray for Linux

### ISSUE THREAD

**Issue by mwglen** [ThePBone/GalaxyBudsClient#310]
**Is your feature request related to a problem? Please describe.**
Currently, the Linux version does not have a setting to minimize to the system tray. 

**Describe the solution you'd like**
I would like for there to be a setting to minimize the application to the system tray for Linux. Additionally, I would like to run the galaxybudsclient command with an argument that specifies it to start minimized in the system tray.

**Describe alternatives you've considered**
I've tried minimizing to tray with both alltray and kdocker, but neither can find the id of the created window.

**Additional context**
N/A

**Comment by ThePBone** [comment]
Tray icon support on Linux is implemented. The menu contents of the tray icon may not be fully responsive at the moment due to a bug in the UI framework (https://github.com/AvaloniaUI/Avalonia/issues/8076), but it appears to work well despite that.
If it isn't enabled by default, you can find a toggle for this feature on the settings page. 

You can grab precompiled binaries here (scroll all the way down):
https://github.com/ThePBone/GalaxyBudsClient/actions/runs/2282507080
