### ISSUE TITLE
[BUG] GUI doesn't appear on the arm64 Windows build 

### ISSUE THREAD

**Issue by willamettefour** [ThePBone/GalaxyBudsClient#317]
**Describe the bug**  
The GUI doesn't appear when running the arm64 Windows build. The program does run, it just doesn't show up.

**To Reproduce**  
Run the program on an arm64 system.

**Expected behavior**  
Program launches with the normal GUI.

**Screenshots**  
![lKnCmRGot4](https://user-images.githubusercontent.com/94886283/166848708-13ef3126-4eb6-4fa1-9ae6-0f28c04fe5c4.png)
![oHFqvtuqUt](https://user-images.githubusercontent.com/94886283/166849640-b1f31876-99f0-46f4-a988-3f4d9c6278e3.png)
![Screenshot 2022-05-04 165513](https://user-images.githubusercontent.com/94886283/166847003-8ba41048-29f1-4522-8630-affe705ee442.png)

**Desktop (please complete the following information):**  
 - OS: Windows 11 Home 64bit 22000.652, English (United States) 
 - Application version: 4.5
 
**Additional context**  
The x64 version works just fine through emulation.

**Log files**  
[application.log](https://github.com/ThePBone/GalaxyBudsClient/files/8627939/application.log)

**Comment by ThePBone** [comment]
Sorry, the native arm/arm64 version for Windows has been dropped. This issue is already known, but I don't have any proper ARM hardware (except a raspberry pi) to troubleshoot this issue, which makes maintaing this app on that platform rather hard.

See issue #285 for details. 

(There shouldn't actually be any Windows ARM binaries attached on the release page, but they were automatically compiled and added to the release by a GitHub workflow I forgot to modify)
