### ISSUE TITLE
[REQ] Want to run at startup on linux, but need a argument to not to open window and just minimize to tray.

### ISSUE THREAD

**Issue by DevL0rd** [ThePBone/GalaxyBudsClient#341]
For one I love the client, works perfectly on linux.

However would like a guide on how to get it running at startup.

I basically can get it running at startup but would like a flag like -startup or -startminimized so it doesn't popup everytime.

Thanks!

**Comment by ThePBone** [comment]
Hey, 

you can use this (Windows-style) command-line switch to launch the app minimized: 
```
galaxybudsclient /StartMinimized
```

This isn't documented anywhere because it was designed to be used by the built-in auto-start setting (currently only available on Windows). I'll also look into implementing that auto-start feature on Linux soon, probably by creating a `.desktop`-entry in `~/.config/autostart`.
