### ISSUE TITLE
[BUG] Developer Options Link Key

### ISSUE THREAD

**Issue by eric781998** [ThePBone/GalaxyBudsClient#343]
**Describe the bug**  
Not exactly a bug with the Manager tool, but I am currently attempting to replicate the dumping of the Bluetooth bonded list and link-keys from the debug features. However, when I am sending the request, I do not get the bonded lists from the output, even when have connected the Galaxy Buds to another computer. Is this an issue you have faced before?

**To Reproduce**  
1. Go to Options -> Settings
2. Go to Developer Options -> Launch Bluetooth socket
3. Once in Developer Tools, find "UNK_DUMP_BONDED_DEVICES" in first selection option 
4. Select "Request" in second selection option 
5. Click Send

**Expected behavior**  
Based off of the GalaxyBudsPlus_HiddenDebugFeatures.md file, there should be a Hex and ASCII output that says, "Show bonded list", as well as a list of other bonded devices. 

**Screenshots**  
![samsung](https://user-images.githubusercontent.com/75996912/175650625-2029ad4e-48a0-4a70-8574-b7cb91d30733.png)

**Desktop (please complete the following information):**  
 - OS: Windows 10 Pro 64 bit 
 - Build Number:  Build 19044
 - Application version: Version 10.0.19044

**Comment by ThePBone** [comment]
Yes, I noticed this too back then when I tested these commands on the Buds Plus. In my case, it would return the complete list at times, and sometimes it would miss the bonded list, especially if I had already received the bonded list once.
I originally planned to include it as a feature to view (and unpair) previously connected Bluetooth devices; however, I dropped that idea because it behaved too inconsistently.

I just retried with my Galaxy Buds Pro, and I can't reproduce this issue anymore for some reason. Unfortunately, I have no clue what kind of condition needs to be fulfilled to have it print out the bonded list.

Also, according to the dump, it looks like you ran that command on the original Galaxy Buds (SM-R170). It could be possible that this model does not have this feature built into its firmware. Perhaps it is only available for Buds+ or later models.
