### ISSUE TITLE
Buds 2 not connecting to Manager [BUG] 

### ISSUE THREAD

**Issue by MoistBalls** [ThePBone/GalaxyBudsClient#344]
**Describe the bug**  
I paired and connected the Buds 2 to my PC, they work fine, even with the app in Windows Store. But with this Client, I keep getting the message "No paired devices found". Both Bluetooth modes show the same result.

**To Reproduce**  
Opening the client v4.5.2, pressing continue and then Refresh paired devices.

**Expected behavior**  
Galaxy Buds 2 should appear on the client saying they are connected.

**Desktop (please complete the following information):**  
 - OS: Windows 10 Pro 64bits OS Build number - 19044.1766, default system language - Portuguese

 - Application version: v4.5.2

**Log files**  
[application.log](https://github.com/ThePBone/GalaxyBudsClient/files/9002194/application.log)

EDIT: Something that didn't occur to me when writing this bug. I am currently not in an administrator account. This is a work PC and I must use it as a non-Admin. Whenever there's something that need admin privileges, I do have another account that I may use in those instances. I installed the Manager using that account, when prompted. Starting the manager with admin privileges doesn't fix the issue.

**Comment by ThePBone** [comment]
I'm filtering the devices by their names and looking for `Galaxy Buds2` in the device name. However, a firmware update added personalized device names like `User's Buds2`, so the devices were filtered out because of their name (see #326). 
I actually thought I fixed it with the last update (v4.5.2) and the person in #326 also reported it to work correctly.

Anyway, could you tell me the device name of the earbuds shown in Windows?
