### ISSUE TITLE
Spanish version support

### ISSUE THREAD

**Issue by efrenbg1** [ThePBone/GalaxyBudsClient#35]
First of all, outstanding work here 👌!

I have found translations for Spanish under the folder i18N. Even though some translations seem weird, are there any plans to include these translations in a future release? 

If so, I would like to make some modifications as to improve reliability, but I am a bit lost in the project structure. Are there any more files containing translations?

**Comment by ThePBone** [comment]
Thanks :+1:
You can find all translatable strings in the i18n folder, there are no separate language files. 

I'm planning to include all translations in this folder but I haven't released a new version since the Spanish and Chinese translations were added. 

Contributions and corrections are always welcome, you can submit a pull-request if there's anything you want to add/change.

**Comment by efrenbg1** [comment]
Perfect! I will get into it as soon as possible, I will let you know then.
