### ISSUE TITLE
\n displaying in several dialogs

### ISSUE THREAD

**Issue by superbonaci** [ThePBone/GalaxyBudsClient#37]
\n is displayed in several dialogs.

![](https://i.imgur.com/vRGA5hw.png)

![](https://i.imgur.com/9Lusqql.png)

Only tested 2 but probably happens on all of them.

**Comment by ThePBone** [comment]
Yes, this happens for all (Windows-styled) message dialogs using linebreaks. Apparently this has been happening ever since I made all strings localizable because xaml (format of the translation files) has in some cases issues with \n.

Normally I should be able to use a html-encoded linebreak instead of \n in those files as well, but for some reason, these message boxes provided by Windows don't display any those characters properly.

I'll look into it soon, it shouldn't be too hard to come up with a small workaround for this.

**Comment by ThePBone** [comment]
Issue fixed. An update is going to be made available soon.
