### ISSUE TITLE
Custom actions not working

### ISSUE THREAD

**Issue by e-t-l** [ThePBone/GalaxyBudsClient#38]
For some reason, my assigned custom long-press actions are not working. I don't even hear the sound that usually indicates a long-press has fired from the earbuds. 

I downloaded this client yesterday for Windows (Win 10 Home 64-bit, v1909, build 18363) and it successfully recognizes my Galaxy Buds (not Buds+). Under the System Information tab, it says...
Hardware version: rev0.4
Software version: R170XXU0ATF2
Touch firmware version: 39
Protocol revision: rev3

Nothing indicates there's anything out of the ordinary (although on the System Information tab, when I click "Run self test," everything just says "fail"... not sure what that's about. 

Any idea why this isn't working? The buds are connected by bluetooth to my computer, recognized by the manager client, and set as the default audio device.

**Comment by filipefumaux** [comment]
I'm having the same issue here. I was trying to configure it to run a key sequence, to mute it during calls. I've tested the right one to run CTRL + SHIFT + M  and the right one just to hit WIN key. Nothing works.
Cheers

**Comment by ThePBone** [comment]
I checked some [error logs](https://sentry.io/share/issue/3c6a82e82ec94f69ab31f683d3a52f99/) I received that seem to be related to your issues:

```
[System.Exception]
Some simulated input commands were not sent successfully.
The most common reason for this happening are the security features of 
Windows including User Interface Privacy Isolation (UIPI).
Your application can only send commands to applications of
the same or lower elevation.
Similarly, certain commands are restricted to Accessibility/UIAutomation applications.
Refer to the project home page and the code samples for more information.
```

This error only occurred on Windows 10 build 18363 and later, so it may be a new change in Windows 10 to protect against malicious apps sending global simulated keyboard events.
I'll try to search for a workaround.

**Comment by ThePBone** [comment]
I did some more research on this and [Microsoft's dotNet documentation](https://docs.microsoft.com/en-us/previous-versions/dotnet/articles/bb625963(v=msdn.10)?redirectedfrom=MSDN#uiaccess-for-ui-automation-applications) state this:

Requirements to bypass UIPI restrictions on sending window messages across privilege levels:
* > The application must have a digital signature that can be verified using a digital certificate that chains up to a trusted root in the local machine Trusted Root Certification Authorities certificate store.
* > The application must be installed in a local folder application directory that is writeable only by administrators, such as the Program Files directory. 

Since I don't own a certificate that chains up to a trusted root (and they are quite costly), it is not possible to bypass the UIPI restrictions that cause your issues with the hotkey custom actions.

It should still be possible to send hotkey events to applications that run on a **lower privilege level** than the Buds Manager.
