### ISSUE TITLE
How can i install it on ubuntu? [REQ]

### ISSUE THREAD

**Issue by baglan01** [ThePBone/GalaxyBudsClient#391]
Hello , that's might be stupid question , but how can I install it on ubuntu 22.04 ?

**Comment by 392781** [comment]
Ran into same issue.  @ThePBone should implement a .deb or something that could be easily installed.

That said, this is a manual work around:

1. Add the `.bin` file under `~/.local/bin/`
2. Make it executable using `chmod +x GalaxyBudsClient<...>.bin` (fill in the rest of the file name)
3. Execute it at least once using `./GalaxyBudsClient<...>.bin` so that the necessary config directories are set up.
4. Download [the icon](https://github.com/ThePBone/GalaxyBudsClient/blob/master/GalaxyBudsClient/Resources/icon_white.ico) and move it to config directory `~/.local/share/GalaxyBudsClient/` or wherever you prefer to keep icons.
5. Lastly, create a `GalaxyBudsClient.desktop` file in `~/.local/share/applications/` with the following:

```
[Desktop Entry]
Encoding=UTF-8
Version=4.5.2
Type=Application
Exec=/home/<your user name>/.local/bin/GalaxyBudsClient_Linux_64bit_Portable.bin
Icon=/home/<your user name>/.local/share/GalaxyBudsClient/icon_white.ico
Name=Galaxy Buds Client
Comment=Unofficial Galaxy Buds Manager for Linux 
```

Log out of your session and log back in and the desktop launchable application should show up with the icon!:
![image](https://user-images.githubusercontent.com/25296775/226215209-330395a3-97eb-458d-a60c-e9acf2bd42a9.png)

This is a local setup, if you want to do it system wide, you should do it via `/usr/bin/` and `/usr/share/`.

If you have any questions, let me know!

**Comment by jarvied** [comment]
On my Debian/KDE system, I can pair my Galaxy Buds2 successfully, but when I try to connect, I get an error "protocol not available". When I run the GalaxyBudsClient, it says "No paired devices found. Please connect and pair your Buds first."

I thought that the purpose of the GalaxyBudsClient was to implement the buds protocol, so that after pairing I should be able to connect via the GalaxyBudsClient. How can I connect them before running GalaxyBudsClient?

**Comment by jarvied** [comment]
I solved my issue thanks to https://wiki.debian.org/BluetoothUser/a2dp. I needed to install pulseaudio-module-bluetooth package.
