### ISSUE TITLE
[BUG] My Galaxy Buds 2 are not found

### ISSUE THREAD

**Issue by AdequaTeC** [ThePBone/GalaxyBudsClient#393]
**Describe the bug**  
My Galaxy Buds 2 are not found. They are paired and connected and I have refreshed and toggled to alternative BT.

**To Reproduce**  

1. Open app
2. Observe problem

**Expected behavior**  
I expected my buds to appear in app so that I can connect to them

**Desktop:**
 - OS: Windows 11 [Home] [64bit] OS Build 22621.1265, English
 
 - Application version: 4.5.1.0

**Additional context**  
I am new to GitHub and have no idea what I am doing so it could very easily be user error.

**Log files**  
[application.log](https://github.com/ThePBone/GalaxyBudsClient/files/10968823/application.log)

**Comment by Ixby** [comment]
I have the same problem - Buds2 Pro - paired and working on the Win10 machine, but the software isn't detecting them.

**Comment by abdullzz** [comment]
i knew it, unlucky!

**Comment by ThePBone** [comment]
You could try to use the manual connection option if it isn't detected automatically. You'll also need to select the correct model if you choose to do that. 
See screenshot:

![image](https://user-images.githubusercontent.com/38386967/228695612-214147b0-7d69-47b5-beb0-c05fda9f7ece.png)

**Comment by luisalvarado** [comment]
If it helps the developers, it works perfectly on Ubuntu 23.04. It detected the galaxy buds pro 2 and I was amazed with all the options working like nothing ever happened. Kudos to the developers.

**Comment by swichers** [comment]
I have two Windows 11 machines. The Galaxy Buds2 Pro are paired on both machines and can successfully play music when connected.

The client does not recognize the Buds2 Pro on either machine. On one machine I was able to manually pair and select my device successfully. On the other I do not get the manual option at all. Instead of "Manual connection" it shows "Back"

**Comment by voedev** [comment]
I am using an ASUS USB-BT400 bluetooth adapter as a second bluetooth module in Fedora 37.

I have successfully connected the galaxy buds2 pro to the system, but the galaxy buds client does not see them, even manual connection does not display any devices. 

![2023-11-07_21-16](https://github.com/ThePBone/GalaxyBudsClient/assets/42519520/5c66441d-cab5-44b0-8b41-285d1f4a80cc)

**Comment by luisalvarado** [comment]
Kudos to the creators of this. It works without any issues on Ubuntu 23.10 also.

**Comment by ThePBone** [comment]
This issue was caused by personalized device names (affects Buds 2, Buds 2 Pro, and Buds FE). 
On most platforms, the Bluetooth stack doesn't expose enough device information for us to detect the device model before connecting. So, we can only rely on the device name; however, with personalized device names, this is becoming unreliable.

For now, the 'Manual connection' button should be used as a fallback. If the button is not there, then you need to update the app.
