### ISSUE TITLE
[REQ] any plans or roadmap for an android app

### ISSUE THREAD

**Issue by rex07** [ThePBone/GalaxyBudsClient#406]
Is there any roadmap or plans for android port reslase

**Comment by ThePBone** [comment]
No, I don't have plans for an Android port.

**Comment by yigitcanustek** [comment]
> No, I don't have plans for an Android port.

Why? Controlling Buds from phone most useful for users or am i wrong? Is there specific reason or policy to not port the program for Android?

**Comment by ThePBone** [comment]
> > No, I don't have plans for an Android port.
> 
> Why? Controlling Buds from phone most useful for users or am i wrong? Is there specific reason or policy to not port the program for Android?

An official Android app from Samsung already exists and this app would need to be rewritten from scratch for mobile devices. An open-source alternative would be nice, but that's too time-consuming to develop and support it for me.

Also, I wouldn't be able to implement more advanced stuff like support for Samsung's scalable audio codec for low latency or 360° Audio since these features are protected by signature-level permissions on Samsung's Android firmware.

**Comment by rex07** [comment]
> > @yigitcanustek try [Gadgetbridge](https://codeberg.org/Freeyourgadget/Gadgetbridge)
> 
> You're life saver. Thanks :)

No problem ; )
