### ISSUE TITLE
[REQ] Iphone app

### ISSUE THREAD

**Issue by ahmednrana** [ThePBone/GalaxyBudsClient#425]
Thanks for this brilliant software.

Is there any possibility of an iphone app?

**Comment by idontknownl** [comment]
to give a bit of context, Samsung does not provide official support in the official IOS app only for galaxy buds live  and the galaxy buds +. I think there are many people like me that would be happy to pay for an IOS third party app that would allow to manage their galaxy buds.

**Comment by ThePBone** [comment]
An iOS version is generally impossible (without a jailbreak) because the Buds mainly use Bluetooth BR/EDR, which Apple heavily restricts. It would require Samsung to license and embed [Apple's proprietary DRM MFi chip](https://stackoverflow.com/a/28473622/11559090) into the earbuds.

Only Bluetooth LE is available without restrictions; however, IIRC only the older earbud models have this additional compatibility with iOS, but Samsung dropped that probably in favor of other features since the space on the flash chip is limited.
