### ISSUE TITLE
[BUG] When downgrading the firmware on my galaxy buds 2 pro, the prompt shows the earbuds as a galaxy buds 2 (2021). Now I have no serial number.

### ISSUE THREAD

**Issue by K0lyei** [ThePBone/GalaxyBudsClient#439]
**Describe the bug**  
Galaxy buds 2 pro show up as "galaxy buds 2 (2021)" in the firmware downgrade page. After installing the firmware, I don't have a serial number, and I can't upgrade these earbuds anymore.

**To Reproduce**  
Steps to reproduce the behavior: Go into Galaxy Buds Manager, system, install firmware updates. 

**Expected behavior**  

**Screenshots**  
![20240101_233715](https://github.com/ThePBone/GalaxyBudsClient/assets/94151321/130a6b02-34eb-4061-9ac9-a53f34aa280f)

**Desktop (please complete the following information):**  
 - OS: Windows 10 iot ltsc enterprise ltsc version 21h2. English language.  Build number 19044.3803
 
 - Application version: 
Galaxy Buds Manager unofficial 4.5.4.1
**Additional context**  

**Log files**  
[application.log](https://github.com/ThePBone/GalaxyBudsClient/files/13807694/application.log)

**Comment by K0lyei** [comment]
[AWA5 firmware works fine](https://www.reddit.com/r/galaxybuds/comments/17g1msn/galaxy_buds2pro_firmware_downgrade_file/). Will upload screenshots later today

**Comment by PirateOfTheCaribbean** [comment]
Normally i would never comment on an issue saying that it works on my machine but since this whole operation is quite risky and here isn't a lot of information around, I just wanted to report that i was able to downgrade from `R510XXU0AWI2` to `R510XXU0AVK3` succesfully without having the serial numbers disappear. 
So downgrading to this version without issues is actually somehow possible. 
I obtained the .bin from [here (reddit)](https://www.reddit.com/r/galaxybuds/comments/18a0lfv/how_to_fix_samsung_galaxy_buds_2_pro_tuning_sound/), its sha256 is`32efc7143f1cc0ebcb374f74e00a453c82b5781b77cae3047464e79b84ef11cd`.
I used version 4.5.1.0 on windows 10 with the alternative bluetooth backend and an intel AC9560.
Various people seem to have your same issue in the above reddit link, not sure if it depends from the buds' manifacturing date (and thus the firmware they were released with), the region they were sold in or something else.
Good to know that updating to a later firmware "fixes it".
 
As a sidenote, attempting to downgrade the firmware on Linux seems to fail when the firmware upload/copy progress reaches 50% with the error "Failed to upload firmware, Time out while waiting for the transfer process to finish"
The upload is also significantly slower in comparison to windows.
 I used ArchLinux with version 4.5.4 of the manager, with two different bluetooth adapters:
 ```
ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
ID 0bda:8771 Realtek Semiconductor Corp. Bluetooth Radio
```
Unfortunately i don't have the logs for this and i'm not going to try it again so opening another issue for these failed uploads wouldn't make much sense(?)

Screenshots:
![Screenshot_20240106_172502_Galaxy Buds2 Pro Manager](https://github.com/ThePBone/GalaxyBudsClient/assets/74542244/3f3f64df-1ae7-4dda-949e-604b9b9976c0)
![Screenshot_20240106_183032_Galaxy Buds2 Pro Manager](https://github.com/ThePBone/GalaxyBudsClient/assets/74542244/2708cbc6-4a70-41dd-9d96-e6c213e514cf)
![image](https://github.com/ThePBone/GalaxyBudsClient/assets/74542244/8f462efb-a153-441c-8f5d-55add1967241)

**Comment by K0lyei** [comment]
I obtained the .bin from the same post on reddit. My galaxy buds 2 pro's I
bought from samsung on November 28, 2023. I am based in the US so these
came by default with AWF4 firmware, through the country code XAR. The buds
were upgraded to the AWI2 firmware.

I downloaded version 4.5.1 of the buds manager program. Now I'm in the
process of downgrading to avk3 firmware. Which gives out a serial number of
0's on both earbuds.

**Comment by K0lyei** [comment]
How do I upload the log files needed in order for you to troubleshoot the
issue?

**Comment by ThePBone** [comment]
According to someone else's report, upgrading the Buds to a later firmware using this app works and restores the serial number again.
Samsung's official app refuses to update when the serial number is zeroed.

You can find my collection of firmware files here: https://github.com/ThePBone/galaxy-buds-firmware-archive
