### ISSUE TITLE
[REQ] A android application ? 

### ISSUE THREAD

**Issue by OverStyleFR** [ThePBone/GalaxyBudsClient#445]
It's possible to do a android application of that ? I would like to use your application instead of Samsung's.

**Comment by ThePBone** [comment]
I don't plan to create an Android port.

However, there's an open-source app called Gadgetbridge that has basic support for the Galaxy Buds: https://gadgetbridge.org/

**Comment by Nico04** [comment]
As a Flutter developer, I might be interested in that project. I'll look into it.

**Comment by OverStyleFR** [comment]
> As a Flutter developer, I might be interested in that project. I'll look into it. 

Ho very nice! The app Gadget Bridge is not what I expected with Galaxy Wearbles

**Comment by OverStyleFR** [comment]
> As a Flutter developer, I might be interested in that project. I'll look into it. 

Did you start the project?

**Comment by Nico04** [comment]
> > As a Flutter developer, I might be interested in that project. I'll look into it.
> 
> Did you start the project?

No I did not, for now it's just a project in my head to be honnest, it won't start it the close futur, I'm quite busy for now unfortunately !
Why so, is there any hurry or envy ?

**Comment by OverStyleFR** [comment]
> > > As a Flutter developer, I might be interested in that project. I'll look into it.
> > 
> > Did you start the project?
> 
> No I did not, for now it's just a project in my head to be honnest, it won't start it the close futur, I'm quite busy for now unfortunately !
> Why so, is there any hurry or envy ?

Ho okay.
And yep, the application that he suggest me (Gadget Bridge) don't do all of the features of the Galaxy Buds manager does. So I search for an app who do this

**Comment by timschneeb** [comment]
I looked into an Android port recently and got one working.
The major UI redesign and code rewrite I released a few months ago, made a mobile version much more feasible than before.

Currently, the only thing missing from the Android port is the ability to let the app run in the background, because of that 'Bixby remap' & custom touch actions (except the built-in actions of course) are unavailable.
________
You can download an APK with the basic feature set here: https://timschneeberger.me/downloads/me.timschneeberger.galaxybudsclient.demo_v5.1.0.1-Signed.apk 
(if you're wondering about the big APK size, this is a universal build that includes binaries for all common CPU architectures)

I've decided to only provide advanced features (FW up-/downgrading, multi-device, etc...) in a paid Play Store version though: https://play.google.com/store/apps/details?id=me.timschneeberger.galaxybudsclient

**Comment by OverStyleFR** [comment]
> I looked into an Android port recently and got one working. The major UI redesign and code rewrite I released a few months ago, made a mobile version much more feasible than before.
> 
> Currently, the only thing missing from the Android port is the ability to let the app run in the background, because of that 'Bixby remap' & custom touch actions (except the built-in actions of course) are unavailable.
> 
> You can download an APK with the basic feature set here: https://timschneeberger.me/downloads/me.timschneeberger.galaxybudsclient.demo_v5.1.0.1-Signed.apk (if you're wondering about the big APK size, this is a universal build that includes binaries for all common CPU architectures)
> 
> I've decided to only provide advanced features (FW up-/downgrading, multi-device, etc...) in a paid Play Store version though: https://play.google.com/store/apps/details?id=me.timschneeberger.galaxybudsclient

Okay, so you made a Android version of it ? What's the problem ? Why you don't tell about this ?

**Comment by OverStyleFR** [comment]
I buy the app on the play store. Work perfectly!
I don't see the statistics, like the battery etc... That's the thing you can't work for android?

**Comment by timschneeb** [comment]
Not yet, but I'll look into adding that later.

At the moment, the app cannot run in the background on Android, because the way Android background services work, is fundamentally different from desktop environments.
I need to rewrite parts of that code first before stuff like battery statistics can work properly.

**Comment by OverStyleFR** [comment]
> Not yet, but I'll look into adding that later.
> 
> At the moment, the app cannot run in the background on Android, because the way Android background services work, is fundamentally different from desktop environments. I need to rewrite parts of that code first before stuff like battery statistics can work properly.

Ho okay, i see.
Thanks for making an Android application ! I bought it on the Google Play Store ^^
