### ISSUE TITLE
[REQ] Galaxy Buds Pro 2 needs voice detect feature support!!!!

### ISSUE THREAD

**Issue by Weltolk** [ThePBone/GalaxyBudsClient#473]
**Is your feature request related to a problem? Please describe.**

Currently in a completely unusable state, when I play the game, the voice detection feature causes, whenever I speak, any other voices (including other people's voices) to be lowered to the point where I can't hear what others are saying

**Describe the solution you'd like**

Supports turning voice detection off and on

**Describe alternatives you've considered**

Turning it on and off on your cell phone, which is obviously a pain in the ass.

**Additional context**

I noticed that there is a similar feature called "Use ambient sound during calls", but turning it off doesn't work, it only works if you turn it off from your phone and then connect it to your computer.

**Comment by ThePBone** [comment]
There was a bug that detected your Buds2 Pro as a pair of Buds2. Because the Buds2 don't support voice detect, the toggle switch for it was mistakenly hidden.

The latest update fixes this issue: https://github.com/ThePBone/GalaxyBudsClient/releases
However, you still need to unregister the device and redo the connection setup so that this time, the earbuds get correctly recognized as a pair of Buds2 Pro.
