### ISSUE TITLE
[REQ] As the client exe already works standalone, please release a portable version

### ISSUE THREAD

**Issue by rollercoaster** [ThePBone/GalaxyBudsClient#481]
**Is your feature request related to a problem? Please describe.**
I am a long time user and I have always just opened the windows setup using 7z and extracted the main exe to put in a folder to use. I wonder if we need an installer at all. All the other files in the setup.exe seem to be .pdb and setup related files.

![image](https://github.com/ThePBone/GalaxyBudsClient/assets/578962/75af724c-1e9e-4d26-a578-1961a0572900)
![image](https://github.com/ThePBone/GalaxyBudsClient/assets/578962/df7e441f-1412-4a56-810e-f677dce20396)

**Describe the solution you'd like**
I think a direct 'Galaxy Buds Client.exe' release (or in a .zip) would be great for power users.

**Comment by ThePBone** [comment]
Sure, I've attached a portable Windows binary to the latest release. 

It's a bigger download because it isn't compressed, and it bundles the NET runtime.
I haven't packed it inside a ZIP for now because, on my machine, Windows Defender recently falsely flagged a ZIP with this app's setup wizard as a threat (while the standalone setup exe was fine).
