### ISSUE TITLE
Compile on Linux

### ISSUE THREAD

**Issue by superbonaci** [ThePBone/GalaxyBudsClient#5]
Hi, could be possible to compile this app natively on Linux, since relies on .NET?

**Comment by ThePBone** [comment]
No sorry, this app makes use of WPF (UI engine) which is Windows only. (Cross-platform support was planned at first since I thought I could simply use .Net Core to run it on Linux, but that's not really an option now).

As a frequent Linux user, I think I'm going write an app for Linux (and in theory macOS + Android) using C++/QML from scratch. 
I can't provide an ETA for now, but I'll probably start working on it soon.

**Comment by superbonaci** [comment]
We've been trying to get more detailed information using Python, but we've got so far the reported common battery level, with "BIEV=2,80" where 80 is the percentage.
https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level

**Comment by ThePBone** [comment]
I can have a look at their python script.

They seem to use somewhat standardized Rfcomm protocol to receive AT messages. Implementing the proprietary and custom Rfcomm protocol used for more advanced information is an overkill since it would add 200+ lines of code to this tiny universial 60-lines script just for better compatibility with the Buds.

However, I found a few interesting unstandardized samsung AT commands while reversing the Firmware of the Buds. Maybe I can use it to get more detailed battery statistics this way.

**Comment by ThePBone** [comment]
No success, unfortunately. The easiest way to get more detailed information would be to implement the custom RFCOMM protocol Samsung uses. But as I said before, this would significantly bloat their universal(!) script with a lot of complex lines of code, which is definitely a complete overkill.

**Comment by superbonaci** [comment]
Thank you very much.

**Comment by nvixonimo** [comment]
> No success, unfortunately. The easiest way to get more detailed information would be to implement the custom RFCOMM protocol Samsung uses. But as I said before, this would significantly bloat their universal(!) script with a lot of lines of complex code, which is definitely a complete overkill.
> 
> Creating a separate repo for this would be better, but that's a rather low priority for me since I'm working on a Linux port for the manager app anyway.

Does that mean there will be full support of HFP/HSP profile for Buds/Buds+ so that it would be possible to use the microphone without sacrificing sound quality?

**Comment by ThePBone** [comment]
Your host device should already provide HFP support based on the standard specification. Or do you mean something different with *full* support? (Maybe full AT command support used in the HFP protocol?)
I never used the built-in microphones so I can't really judge the microphone quality.

**Comment by nvixonimo** [comment]
> Your host device should already provide HFP support based on the standard specification. Or do you mean something different with *full* support? (Maybe full AT command support used in the HFP protocol?)
> I never used the built-in microphones so I can't really judge the microphone quality.

To put it simply - currently Buds cannot be used as headset on Linux - with working microphone input and decent output quality. There is a workaround using ofone, which enables HFP for the Buds, but, as mentioned, overall sound quality becomes awful and unusable for videoconferencing. 

My question is -- will your port provide some sort of solution to that problem? So that both mic and general sound are at least average quality with HFP/HSP enabled?

**Comment by ThePBone** [comment]
Well, the manager app itself does not mess with HFP but I'll try to look into it when working on the port. Maybe I can find something useful but I can't guarantee anything yet

**Comment by superbonaci** [comment]
> To put it simply - currently Buds cannot be used as headset on Linux (with working microphone input and decent output quality). There is a workaround using ofone, which enables HFP for the Buds, but, as mentioned, overall sound quality becomes awful and unusable for videoconferencing.
> 
> My question is -- will your port provide some sort of solution to that problem? So that both mic and output sound are at least average quality with HFP/HSP enabled?

Does anybody know of headsets can be used properly with macOS? I guess Airpods* should work perfect for music, calls, and everything the same as on iPhone. But probably with other buds you couldn't do it.

**Comment by nvixonimo** [comment]
So I looked a little more into the mic problem - actually support for HSP is needed, HFP is kind of already there. 

It does look complicated - tried to find solutions in bluez (also found a list of some HSP supported devices, no info on galaxy buds) and blueman to maybe enable the profile, no luck. 

So if you do find a solution, in a sense that would be lifesaving :)

**Comment by lexatisa** [comment]
Not problem Mic

**Comment by ThePBone** [comment]
A Linux port is now available (beta): https://github.com/ThePBone/GalaxyBudsClient/issues/57#issuecomment-752146189

**Comment by alb-p** [comment]
@sepp0 did you find any accetable workaround for microphone problem?

**Comment by stingray21** [comment]
Did anyone get the mic working on Linux?
