### ISSUE TITLE
Linux port?

### ISSUE THREAD

**Issue by marvic2409** [ThePBone/GalaxyBudsClient#57]
I saw in a previous closed issue that you stated that you were working on a linux/macos port. I am currently running linux and was wondering if I could somehow help out with the development/testing?

**Comment by ThePBone** [comment]
Currently, only the Bluetooth backend for the Linux port is done.
At first, I planned to create a separate project written in C++/QML but I wanted to avoid having to maintain two separate projects, so I decided to port the existing app to .NET Core for Linux support instead. Unfortunately, my current UI toolkit (WPF) and Bluetooth library are Windows-only. 
I already wrote a .NET Core library for Bluetooth RFCOMM communication via Bluez which already works flawlessly, but switching to a new UI toolkit ([AvaloniaUI.NET](https://github.com/AvaloniaUI/Avalonia)) is going to be very time-consuming and hard since I have to rewrite all UI elements (and add cross-platform support for stuff like notification popups, auto-start, custom touchpad actions, ...).

I haven't started porting the UI to the new toolkit yet (and I don't know when I'll begin, maybe in a week or two). If you know a little bit of XAML and/or C# you could try to 'rebuild' one or more menus/layouts using the new UI toolkit, but other than that there's nothing that could be tested atm.

macOS support was dropped (by me at least), the platform is too developer-unfriendly if you don't own any Apple devices to test on. Virtual machines are super slow and don't even properly work without spoofing CPU and GPU to work around Apple's restrictions. I don't think it supports PCI passthrough anyway, so I wouldn't be able to access my Bluetooth adapter from the VM.

**Comment by k----n** [comment]
@ThePBone 
I'm possibly interested in helping port the UI.

Are you referring to this branch? https://github.com/ThePBone/GalaxyBudsClient/tree/bluez-backend

How do you plan to structure the app?

I'd also like to emulate your dev environment, it seems like you're using Rider IDE.
Were you planning to use this plugin for Avalonia? https://github.com/ForNeVeR/AvaloniaRider

**Comment by ThePBone** [comment]
Yes, that's the branch. However, it only contains my Bluetooth EDR/BR library for Linux and another demo project (DBusTest.csproj) to test it at the moment. 

I'm planning to structure it the same way as the current version: one rounded window with a page container (-> ContentPresenter) that can switch its child dynamically with interpolated transitions.

I'm using the latest JetBrains Rider package from the early access program. The EAP version has experimental Avalonia support and is free-to-use for everybody. (https://www.jetbrains.com/rider/nextversion/)

**Comment by ThePBone** [comment]
The port is mostly finished. Some stuff such as the tray bar integration is still missing, but this should be mostly usable.

Here is a beta build, just extract it somewhere and run the `GalaxyBudsClient` executable. This is a self-contained build, no dependencies required.

Beta downloads: <https://nightly.timschneeberger.me/galaxybudsclient/>

I don't support Linux setups that use proprietary NVIDIA drivers due to severe bugs/incompatibilities with the rendering backend (libSkia). You can still try but expect sudden crashes and segfaults.

**Comment by Anti-Apple4life** [comment]
How do I make this work on MacOS?

**Comment by ThePBone** [comment]
That's not possible because there are no implementations of some platform-specific services for macOS at the moment. 
The user interface part would probably run without any issue but on macOS, there are implementations for several modules missing:
* Bluetooth backend ([IBluetoothService](https://github.com/ThePBone/GalaxyBudsClient/blob/master/GalaxyBudsClient.Bluetooth/IBluetoothService.cs))
* Tray icon implementation ([ITrayIcon](https://github.com/ThePBone/GalaxyBudsClient/blob/master/GalaxyBudsClient.Interop.TrayIcon/ITrayIcon.cs))
* Auto-start management ([IAutoStartHelper](https://github.com/ThePBone/GalaxyBudsClient/blob/master/GalaxyBudsClient/Platform/Interfaces/IAutoStartHelper.cs))
* Global play/pause media key ([IMediaKeyRemote](https://github.com/ThePBone/GalaxyBudsClient/blob/master/GalaxyBudsClient/Platform/Interfaces/IMediaKeyRemote.cs))

I don't own any macOS devices and that OS has horrible VM compatibility so I won't add support for it myself. If you or anyone else is interested in adding support and has a bit of C# .NET Core experience, go for it.

**Comment by whale124** [comment]
Dear ThePBone, I have some error.
Ubuntu 20.10/AMD 5 4500H

Thank You!! (and sorry for my poor English..)
[error.txt](https://github.com/ThePBone/GalaxyBudsClient/files/5820600/error.txt)

**Comment by Anti-Apple4life** [comment]
If anyone has a Virutal Machine, they could try to make a port!

[Johnny Everman - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=uyqyd)	[uyqyd]

On January 15, 2021 at 12:59 GMT, whale124 <notifications@github.com> wrote:

Dear ThePBone, I have some error.
Ubuntu 20.10/AMD 5 4500H

Thank You!! (and sorry for my poor English..)
[error.txt](https://github.com/ThePBone/GalaxyBudsClient/files/5820600/error.txt)

**Comment by ThePBone** [comment]
@whale124 It looks like you ran the app with root privileges. (Look at line 2 in the log, it has set its config directory to /root instead of your actual home directory)

 Try to start to like a regular app without 'sudo' in front of the command.

**Comment by whale124** [comment]
@ThePBone same 😭️😭️

**Comment by ThePBone** [comment]
@whale124 What Linux distro are you using?

**Comment by whale124** [comment]
@ThePBone Ubuntu 20.10/Kernel 5.10.7-051007-generic

**Comment by ThePBone** [comment]
@whale124 I've set up a Ubuntu 20.10 VM and can reproduce your issue. 
For some reason, the font manager fails to load any fonts when the system language is set to Korean. 

Until I come up with a better fix you can run this app like this:
```
LC_ALL=C ./GalaxyBudsClient
```
This `LC_ALL=C` part makes sure that the GalaxyBudsClient command gets launched using the C language (always corresponds to English)

**Comment by whale124** [comment]
@ThePBone Wow.. It works very well!! Thank You!!

**Comment by ThePBone** [comment]
Stable precompiled binaries for Linux are now available: https://github.com/ThePBone/GalaxyBudsClient/releases/tag/4.0.0.0

I'll also create AUR packages for Arch soon.

**Comment by stingray21** [comment]
Thanks for the work. Is the package already in AUR? I couldn't find it

**Comment by ThePBone** [comment]
It is now in the AUR: https://aur.archlinux.org/packages/galaxybudsclient/

```
yay -S galaxybudsclient
```

**Comment by Rogergonzalez21** [comment]
Hey! Sorry for resurrecting a closed issue, but it looks like galaxybudsclient was removed from the aur :confused: Did something happened?

**Comment by ThePBone** [comment]
The AUR package was originally built using GitHub Actions and then automatically deployed to the AUR whenever I created a new release tag on GitHub. 
Several people were complaining about various issues with it, but since I haven't been using Linux frequently for months and I'm not too knowledgeable about AUR packaging in general, I chose to stop supporting and disown the package (and allow other people to take ownership and apply whatever fixes they had).

Anyway, it seems someone already submitted a deletion request for the orphaned AUR package; that is why it has been deleted. (https://lists.archlinux.org/pipermail/aur-requests/2021-August/057180.html)
