### ISSUE TITLE
UI issues + Possible Bug

### ISSUE THREAD

**Issue by ArthurWolfhound** [ThePBone/GalaxyBudsClient#61]
Hi!
First of all, please let me know if you have any new strings for translation except the one about primary screen, because I am currently under high workload in the university.

# UI Bug with Language List
Secondly, there's a bug that causes language list to shorten if it doesn't fit onto the screen.
![image](https://user-images.githubusercontent.com/16789106/99713008-85a72f80-2aac-11eb-906c-95c93134c975.png)
![image](https://user-images.githubusercontent.com/16789106/99713144-a079a400-2aac-11eb-8e96-17e694244eb5.png)

# Installer bug
As mentioned in #51, I can also add that installer maintains same behavior on upgrade. 

# Multi-monitor implementation bug.
I can't reproduce #60 but what I can add that if somebody like me uses external monitor and sets it as main screen in Windows Settings - toggling Primary screen only will result in pop-up being unable to show. You might've implemented primary screen logic maintaining primary as built-in but not as system-set primary.

Thanks a lot, and congratulations on your stars!

**Comment by ThePBone** [comment]
> UI Bug with Language List

I moved all lists/context menus into a ScrollViewer to add scrolling support (commit 09e45372)

> Installer bug

Fixed with commit 13f1286b

> Multi-monitor implementation bug

I can reproduce #60, the "new" API I'm using to get the coordinates of secondary and other non-primary screens ignores display settings from the system control panel settings. This API was actually part of Microsoft WinForms (not Microsoft WPF, the UI toolkit I'm currently using) and it calculates coordinates in pixels, not in WPF's scaling-aware measurement unit.

Anyway, I guess I have to revert these changes and keep using the WPF screens API for now (which doesn't provide access to non-primary screens, unfortunately).
But I'm rewriting the whole UI of this app using Avalonia.UI which is cross-platform compatible, so I can finally support Linux as well. Eventually, that version will replace the current app built with WPF and maybe I can implement proper multi-screen support for that one instead.
