### ISSUE TITLE
[REQ] Windows 10 toolbar to Connect on Click

### ISSUE THREAD

**Issue by Mav3r1x** [ThePBone/GalaxyBudsClient#67]
If buds are paired to windows pc, then you just need to go to settings and click on the title to connect (if buds are previously connected to your phone or another device).

A keyboard shortcut or a toolbar to perform this action on one click would make the whole thing faster.

**Comment by ArthurWolfhound** [comment]
Am I correct to believe that you are proposing a feature to have an "Initiate connection" button in the menu?
Addressing lack of response from developer: application is currently under complete rebuild, but I believe he will file your proposal for future.

**Comment by Mav3r1x** [comment]
Correct. A "Connect" button in the tray icon's menu or better a keyboard shortcut to Initiate "Connect".

**Comment by ThePBone** [comment]
Done, I've added a 'Connect' menu item for the tray menu when no device is connected.
However, it'll take a while until an update is ready because I'm rebuilding everything from scratch at the moment.

Also, I'm thinking about adding multi-device support (not in foreseeable future though), in that case, I'd need to come up with a better solution for this issue.

I'll leave this open until a stable update is published.

**Comment by ThePBone** [comment]
A new version that includes this feature is now available: https://github.com/ThePBone/GalaxyBudsClient/releases/tag/4.0.0.0

You can now also define a global hotkey to connect to your earbuds.
