### ISSUE TITLE
[REQ] keyboard hotkeys to replace touch-actions

### ISSUE THREAD

**Issue by gowl** [ThePBone/GalaxyBudsClient#75]
It is inconvenient to lift my hand off the keyboard/mouse to long-tap my headphones and toggle the _ambient mode_ every time I need to speak to somebody. I believe it would be neat to have **hotkeys** to quickly toggle it on or off along with various customizable actions such as pause/unpause but I _personally_ already have another software to take care of volume/music. **Ambient mode** though is the main problem here. Thanks!

**Comment by ArthurWolfhound** [comment]
I personally don't know if keyboard shortcuts would be of any use, but have you checked tray menu?
![image](https://user-images.githubusercontent.com/16789106/101624303-6f90ed00-3a22-11eb-82d6-d53c98b852b3.png)

**Comment by gowl** [comment]
@ArthurWolfhound It's definitely more helpful than nothing. I would still rather have a keyboard shortcut, but it certainly saves me the effort of lifting my hand, so thanks! I'll keep the issue open in-case the owner finds it easy to implement. 😀

**Comment by gowl** [comment]
@ThePBone Hi! I saw that you're using the board to manage the issues. Would you say this could go into the to-do column? 

And good luck on the rebuild! I'll be waiting patiently to use the new release. :)

**Comment by ThePBone** [comment]
Sure, I moved it into my todo-list.

**Comment by ThePBone** [comment]
Sorry for the delay on this. At the moment, I can't include this in the app because I don't have enough time to create more UI components to manage custom hotkeys chosen by a user. **I'll integrate a proper hotkey feature (and an editor for easier customization) with more actions sometime soon.** But if you want to try a "hacky" solution keep reading.

The next version includes some big changes including automation using external C# user scripts. That way, I can just write a small script that is loaded dynamically and registers global Windows hotkeys instead.

Anyway, here are the installation instructions:

You can download the latest builds here (GitHub account required to download): <https://github.com/ThePBone/GalaxyBudsClient/actions?query=workflow%3A%22Compile+Windows+binaries%22>

1. After visiting the link above, select the latest job at the top that finished successfully
2. Scroll all the way down to the artifacts section
3. Select your architecture (32/64-bit) and choose whether you want an installer or standalone executable.
4. Run the setup or extract the standalone version somewhere

Now you need to retrieve a hotkey script file. Currently, I have added two of those scripts with different key mappings:

[GlobalHotkeyReceiver.cs](https://github.com/ThePBone/GalaxyBudsClient/raw/master/scripts/GlobalHotkeyReceiver.cs) (Rightclick > Save link as...)

| Keycombo           | Action          |
|--------------------|-----------------|
| Ctrl + Volume up   | Ambient louder  |
| Ctrl + Volume down | Ambient quieter |
| Ctrl + Volume mute | Toggle ambient  |
| Ctrl + Shift + P   | Play/Pause      |

Or this one: [GlobalHotkeyReceiverAlt.cs](https://github.com/ThePBone/GalaxyBudsClient/raw/master/scripts/GlobalHotkeyReceiverAlt.cs) (Rightclick > Save link as...)

| Keycombo          | Action          |
|-------------------|-----------------|
| Ctrl + Alt + Up   | Ambient louder  |
| Ctrl + Alt + Down | Ambient quieter |
| Win + F2          | Toggle ambient  |
| Ctrl + Alt + P    | Play/Pause      |

If you don't like these predefined maps, you can either modify them or send me your preferred key combos (or additional actions) and I'll change them respectively.

If you haven't already, open the new GalaxyBudsClient app. This is important to make sure that some important directories have been created.

Now open `%LOCALAPPDATA%\GalaxyBudsClient\scripts` in the explorer and paste the script file you've downloaded earlier there.
(You can copy that path into the run-box or into the explorer address bar)

Finally, you need to restart the app to reload all scripts. (make sure the app isn't running in the tray bar before restarting, otherwise, it'll just redirect to the older instance already running in the background)

**Comment by gowl** [comment]
I am shocked and grateful at how well you've handled my issue. Respect. I will try this hacky method sometime soon and report back.

**Comment by ThePBone** [comment]
@gowl A keyboard hotkey editor is now on-board, this didn't even take up too much time after all.

You can download the latest build using the exact same instructions I attached to my last message. If you still have the script in `%LOCALAPPDATA%\GalaxyBudsClient\scripts` you need to remove it to avoid conflicts.

![image](https://user-images.githubusercontent.com/38386967/104845796-91aa4480-58d7-11eb-8066-7dcc39bb2207.png)

**Comment by ThePBone** [comment]
A new version that includes this feature is now available: https://github.com/ThePBone/GalaxyBudsClient/releases/tag/4.0.0.0
