### ISSUE TITLE
Read buds individual battery level

### ISSUE THREAD

**Issue by superbonaci** [ThePBone/GalaxyBudsClient#8]
According to this report, with regular AT commands you can read individual battery level for each earbud.
Is this the same you reverse engineered? What do you think about that approach?
[Dissection improvement: individual battery level for SM-R170 earbuds](https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=16615)

**Comment by ThePBone** [comment]
I connected them to my computer and wrote a small C# app that could directly connect to the rfcomm interface and dump the raw incoming byte stream (using the 32feet C# Bluetooth library).

I never checked Android's HCI log, but I noticed while disassembling the Buds plugin app that it would dump some useful information to the Logcat (IIRC this included hex-dumps of outgoing SPP messages)

There might be some other interesting stuff hidden in their Logcat but I haven't checked that.

**Comment by superbonaci** [comment]
I will try to replicate the data with newer firmware (in case it's available for me).

**Comment by superbonaci** [comment]
I've updated also from R170XXU0ATD37 to R170XXU0ATF2. New version says "Implemented stability code for device security". Will try to detect the battery level for each bud if I can.

**Comment by superbonaci** [comment]
Tried with R170XXU0ATF2 and the parameters are still in place. Look at snoop log with hex editor, look for `Buds`, if it starts at 1st position, then the 17th position and 18th indicate the values for left and right earbuds.

````
42 75 64 73 00 00 00 00 00 00 00 00 00 00 00 00 64 64 00
B  u  d  s  .  .  .  .  .  .  .  .   .  .  .  .  d  d .
````
Where `0x64` mean 100% battery for each earbud.

I have no idea how to trigger that line using Linux for example.

**Comment by ThePBone** [comment]
I did a small test and captured the bt-snoop log from Android and a separate log on my Linux machine.
After comparing both logs in Wireshark, I noticed that the Android log would mention Bluetooth LE packets while the other log from my Linux machine didn't even receive one single BLE packet.
Even after manually attempting to connect my PC to the BLE interface(?) of the Buds using the command line I got nothing. (maybe this is just an issue with my Bluetooth adapter in my PC, but who knows...)

It also looks like Android sends some extra commands to the internal Bluetooth controller in order to configure several BLE settings, my Linux machine doesn't do any of that. (at least not automatically, but I didn't find anything that should have been enabled/configurated beforehand)

I'll just drop both logs here in case you want to look at them in Wireshark:
[btsnoop_android.log](https://github.com/ThePBone/GalaxyBudsClient/files/4852441/btsnoop_hci.log)
[btsnoop_linux.log](https://github.com/ThePBone/GalaxyBudsClient/files/4852446/linux_bt_log.log)

I'll also try to write a small python script that can read the battery levels with the custom rfcomm protocol (instead of BLE) later

**Comment by ThePBone** [comment]
Here is the Python script which is capable of reading both battery levels and wearing statuses (tested on Linux):
<https://github.com/ThePBone/GalaxyBuds-BatteryLevel>

PyBluez is much easier to write for than I expected, the important parts only occupy ~60 lines of code.
You can reuse that small script if you want to merge it into the repo you mentioned the other day: (<https://github.com/TheWeirdDev/Bluetooth_Headset_Battery_Level>)

**Comment by superbonaci** [comment]
Works perfect here with my Buds. I would add also to Requirements that it requires python3, since on my Ubuntu python just points to python2 even having python 3 installed. Even by default you can't configure python3 as alternative for pyhon.
```
python3 buds_battery.py [-h|-v|-w] <MAC>
```
```
ls -l /usr/bin/python
lrwxrwxrwx 1 root root 7 Apr 15 12:45 /usr/bin/python -> python2
```
```
ls /usr/bin/python*
/usr/bin/python     /usr/bin/python3           /usr/bin/python3-config      /usr/bin/python3-wsdump
/usr/bin/python2    /usr/bin/python3.8         /usr/bin/python3-futurize
/usr/bin/python2.7  /usr/bin/python3.8-config  /usr/bin/python3-pasteurize
```
```
update-alternatives --list python
update-alternatives: error: no alternatives for python
```

**Comment by superbonaci** [comment]
I see you are using `#!/usr/bin/env python3` but for some reason doesn't work on ubuntu.

**Comment by superbonaci** [comment]
I've found the problem. If you call the script with python first, it will force to use the version you specify, overriding python env. If you call the script directly will use env.

`./buds_battery.py` -> Reads `#!/usr/bin/env`
`python* buds_battery.py` -> Uses the specified version overriding `#!/usr/bin/env`

**Comment by ThePBone** [comment]
I've updated the README to mention python 3.x and to use python3 instead of python. `3cb0112`

**Comment by ThePBone** [comment]
[GalaxyBuds-BatteryLevel](https://github.com/ThePBone/GalaxyBuds-BatteryLevel) supports now the Buds+ as well.

I'll close this now, but feel free to reopen

**Comment by superbonaci** [comment]
I see that you use the uuid `00001102-0000-1000-8000-00805f9b34fd` to receive the data. Do you know if that attribute has the ability to notify on change? That way you could keep outputting the battery value as it changes, because the buds would actively notify on battery change:
```
/buds_battery.py [-m|--monitor] <mac>
```
Output:
```
100,100 at 2020-07-04T16:07:25.15Z
100,95 at 2020-07-04T16:26:45.36Z
95,95 at 2020-07-04T16:27:45.36Z
```
Date can be obtained with ``date -u +'%FT%T.%2NZ'``
[Date and Time Formats](https://www.w3.org/TR/NOTE-datetime)

**Comment by ThePBone** [comment]
Nice idea. Yes, the Buds send status updates regularly to the client. I'll add it to the script later

**Comment by superbonaci** [comment]
I see your Windows app updates very frequently, but maybe you are refreshing actively times/second, or do you use any wait() function and update values upon trigger?

**Comment by ThePBone** [comment]
The Windows app uses the debug mode to read more advanced stuff like the voltage, temperature, ... which makes it a bit more complicated and requires me the actively refresh those values.

It works like this:
* Buds send simple status updates if the battery value has changed (automatically)
* If the app receives one status update it will call a hidden debug feature to update the advanced values (apart from battery percentages) as well
* This hidden debug feature is called every 12 seconds to stay updated, but only while the main page is visible.

If we only want the basic battery values, then listening for status updates form the Buds is enough. Actively sending update requests is not necessary.

**Comment by superbonaci** [comment]
The hidden debug feature is ever called by the companion app / and / or plugins?
Did you look into the Wear app only ([com.samsung.android.app.watchmanager](https://play.google.com/store/apps/details?id=com.samsung.android.app.watchmanager)) or did you check also into the [Galaxy Buds Plugin app](https://play.google.com/store/apps/details?id=com.samsung.accessory.fridaymgr) and [Buds+](https://play.google.com/store/apps/details?id=com.samsung.accessory.popcornmgr)?

**Comment by ThePBone** [comment]
I only looked into the Plugin apps, I didn't bother to check the Weareable app itself out since it is just a container for these plugins.
And yes, the debug feature (DEBUG_GET_ALL_DATA) is actually called, but only inside a debug menu.

I recently found the hidden debug menu for the Buds+ which allows you to call that feature: <https://www.reddit.com/r/galaxybuds/comments/hjgfaf/galaxy_buds_i_found_a_new_debug_menu/>

The debug menu for the older Buds (and IconX) has been known for a longer time and is easier to access: <https://www.reddit.com/r/galaxys10/comments/bltsq1/galaxy_buds_debug_menu_found_in_galaxy_wearable/>

**Comment by superbonaci** [comment]
Are you able to get the list of attributes using the bluez command `/usr/bin/bluetoothctl` ? Wonder if battery levels can be obtained with this command.

`sudo bluetoothctl` -> `connect <MAC>` -> `info` -> displays:
```
[...]
UUID: Vendor specific           (00001102-0000-1000-8000-00805f9b34fd)
[...]
```
I tried `menu gatt` -> `list-attributes` but doesn't output anything. Don't know if that's the proper way to do it.
```
attribute-info 00001102-0000-1000-8000-00805f9b34fd
Attribute 00001102-0000-1000-8000-00805f9b34fd not available
```

**Comment by ThePBone** [comment]
`GATT` is part of Bluetooth LE.
However, this `00001102-0000-1000-8000-00805f9b34fd` is an SDP record UUID (Classic Bluetooth, not LE), so you can't list any GATT attributes.

**Comment by ThePBone** [comment]
Usually, you can list raw SDP service records using:
```
sdptool records 20:DF:B9:4C:90:D0 
```

**Comment by ThePBone** [comment]
This is rather low-level information though. If you need data like battery statuses you need to connect to their rfcomm interface. There isn't really a way around that.

In the SDP record (see message above) you can see this:
```
  "RFCOMM" (0x0003)
    Channel: 2
```
So you'd need to connect to channel 2 in order to get access to the actual rfcomm protocol:
```
sudo rfcomm connect -i <MAC> 2
```
Then you can write/read to/from `/dev/rfcomm0` in order to communicate with the device.

Open another terminal and execute this command to read incoming data:
```
sudo cat /dev/rfcomm0 | hexdump -C
```
You should now see the raw incoming byte-stream which also contains those status updates, but need to be parsed and decoded ofc.

**Comment by ThePBone** [comment]
> Do you know if any of those attributes have the ability to notify on change? That way you could keep outputting the battery value as it changes because the buds would actively notify on battery change

Sorry for the delay. I finally added the 'monitor' feature to the script:
```
❯ python buds_battery.py 80:7B:3E:21:79:EC --monitor-timestamp
93,96,98,2020-07-19T13:21:10.18Z
93,96,99,2020-07-19T13:21:35.56Z
```
And without timestamps:
```
❯ python buds_battery.py 80:7B:3E:21:79:EC --monitor
97,81,86
96,81,86
96,82,86
```
<https://github.com/ThePBone/GalaxyBuds-BatteryLevel>

**Comment by superbonaci** [comment]
Thanks, tested and working.
