### ISSUE TITLE
Galaxy Buds Pro

### ISSUE THREAD

**Issue by techied** [ThePBone/GalaxyBudsClient#82]
With the rumored upcoming / confirmed Galaxy Buds Pro, how can I / we / the community help to get you a pair to add support?

Would you consider adding a [FUNDING file](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository) so we can donate?

**Comment by ThePBone** [comment]
I considered that a while ago, but I haven't set any of that up at all. 

Anyway, it should be easily possible to implement Buds Pro support without owning them by (worked out for the Buds Live as well).  It just need someone to test my implementation. 

I can start adding Buds Pro support very early, since I already have gotten ahold of the official Buds Pro plugin for Android. Also, aside from the hardware features, the bluetooth backend in software is very similar to the Buds Live, so it really shouldn't be too hard.

**Comment by ThePBone** [comment]
I've implemented experimental Galaxy Buds Pro support. Obviously, I can't test this yet but if someone happens to purchase a pair at launch, it would be great if he/she could test it.

You can download the latest builds with Buds Pro support here (GitHub account required to download): <https://github.com/ThePBone/GalaxyBudsClient/actions?query=workflow%3A%22Compile+Windows+binaries%22>

1. After visiting the link above, select the latest job at the top that finished successfully
2. Scroll all the way down to the artifacts section
3. Select your architecture and choose whether you want an installer or standalone executable.
4. Run the setup or extract the standalone version somewhere

![Screenshot](https://user-images.githubusercontent.com/38386967/104667105-a28b6800-56d5-11eb-9f32-8688813210e0.png)

**Comment by hunpulun** [comment]
Buds pro works really well. However, the detection of wearing is a little slow. The positions of ANC and ambient sound have changed.

**Comment by ThePBone** [comment]
Thanks for testing!

> However, the detection of wearing is a little slow.

This is normal, I'm just displaying what the earbuds send to the application. The earbuds usually have a cooldown before they trigger a change of the current wearing status to avoid false-positives.

> The positions of ANC and ambient sound have changed.

Yes, I had to create an alternative layout because ANC and ambient options need to be displayed simultaneously now.

**Comment by ThePBone** [comment]
A new version that includes this feature is now available: https://github.com/ThePBone/GalaxyBudsClient/releases/tag/4.0.0.0

**Comment by gowl** [comment]
@ThePBone I know this is closed but I didn't want to create a new issue. Buds Pro aside, would you consider adding a funding file so we can donate? What you have going on here is a truly wonderful tool and it would be nice if users could give back. 🙂

**Comment by ThePBone** [comment]
@gowl Sure, I've added a ko-fi sponsor link. I'll try to add some alternatives as well.
